apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cron
  namespace: devprojectk
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["echo", "Hello test!!!"]
          restartPolicy: Never